# Generated by Django 5.2.17 on 2026-08-12 21:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data_hora", models.DateTimeField(verbose_name="data e hora")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("cancelada", "Cancelada"),
                            ("concluida", "Concluída"),
                        ],
                        default="agendada",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="profissionais.profissional",
                        verbose_name="profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta",
                "verbose_name_plural": "consultas",
                "ordering": ("-data_hora",),
                "indexes": [
                    models.Index(
                        fields=["profissional", "data_hora"], name="idx_consulta_prof_data"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "agendada")),
                        fields=("profissional", "data_hora"),
                        name="uniq_consulta_agendada_slot",
                    )
                ],
            },
        ),
    ]
