# Generated by Django 5.2.17 on 2026-08-13 03:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "asaas_event_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="id do evento Asaas"
                    ),
                ),
                ("tipo", models.CharField(max_length=80, verbose_name="tipo")),
                (
                    "asaas_payment_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="id Asaas da cobrança"
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de webhook",
                "verbose_name_plural": "eventos de webhook",
                "ordering": ("-criado_em",),
            },
        ),
        migrations.CreateModel(
            name="Cobranca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="valor"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmada", "Confirmada"),
                            ("recebida", "Recebida"),
                            ("cancelada", "Cancelada"),
                            ("falha", "Falha"),
                            ("vencida", "Vencida"),
                            ("estornada", "Estornada"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "split_status",
                    models.CharField(
                        choices=[
                            ("configurado", "Configurado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                            ("bloqueado_divergencia", "Bloqueado por divergência"),
                        ],
                        default="configurado",
                        max_length=32,
                        verbose_name="status do split",
                    ),
                ),
                (
                    "asaas_payment_id",
                    models.CharField(max_length=64, unique=True, verbose_name="id Asaas"),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=128, unique=True, verbose_name="idempotency key"),
                ),
                (
                    "percentual_profissional",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="percentual do profissional"
                    ),
                ),
                (
                    "net_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor líquido"
                    ),
                ),
                ("split_ativo", models.BooleanField(default=True, verbose_name="split ativo")),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobrancas",
                        to="consultas.consulta",
                        verbose_name="consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "cobrança",
                "verbose_name_plural": "cobranças",
                "ordering": ("-criado_em",),
            },
        ),
    ]
