# Generated by Django 5.2.17 on 2026-08-12 21:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome_social", models.CharField(max_length=150, verbose_name="nome social")),
                ("profissao", models.CharField(max_length=100, verbose_name="profissão")),
                ("endereco", models.CharField(max_length=255, verbose_name="endereço")),
                ("contato", models.CharField(max_length=100, verbose_name="contato")),
                (
                    "asaas_wallet_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="wallet Asaas"
                    ),
                ),
            ],
            options={
                "verbose_name": "profissional",
                "verbose_name_plural": "profissionais",
                "ordering": ("nome_social",),
            },
        ),
    ]
